---
# add i386 as steam requires it
- name: Ensure i386 is added, there's no amd64 steam package
  command: dpkg --add-architecture i386
  register: result
  failed_when: "result.rc != 0"
  changed_when: False

- name: Update apt cache
  apt:
   update_cache: yes

# steam has a popup during installation from apt on Debian that
# asks for accepting a license
# https://askubuntu.com/questions/506909/how-can-i-accept-the-lience-agreement-for-steam-prior-to-apt-get-install
# required steam version 1.0.0.50
# only jessie has older than the required version(x.49)
# steam:
#  debconf.set:
#    - data:
#        steam/question: {'type': 'select', 'value': 'I AGREE'}
#        steam/license: {'type': 'note', 'value': ''}
#  pkg.installed:
#    - sources:
#      - steam-launcher: https://steamcdn-a.akamaihd.net/client/installer/steam.deb
#    - require:
#      - debconf: steam
#
# steam needs i386 backports packages installed before it can be installed
# otherwise it ends in package conflicts

# there's a debconf module
# https://docs.ansible.com/ansible/latest/modules/debconf_module.html
# https://stackoverflow.com/questions/19275856/auto-yes-to-the-license-agreement-on-sudo-apt-get-y-install-oracle-java7-instal

- name: accept steam license
  debconf:
   name: "steam"
   question: "steam/question"
   value: "I AGREE"
   vtype: "select"

- name: Install steam
  apt:
   name: steam
   state: present
   # dpkg_options: 'steam   steam/question  select  I AGREE,steam   steam/license   note'
