---
# add i386 as steam requires it
- name: Ensure i386 is added, there's no amd64 steam package
  command: dpkg --add-architecture i386

- name: Create backports sources.list file
  template:
   src: templates/backports.list.j2
   dest: "/etc/apt/sources.list.d/{{ ansible_distribution_release }}-backports.list"
   mode: 0644
   backup: yes

- name: Install backported mesa amd64 and vulkan
  apt:
   name:
     - libegl-mesa0:amd64
     - libegl1-mesa:amd64
     - libgbm1:amd64
     - libgl1-mesa-dri:amd64
     - libgl1-mesa-glx:amd64
     - libglapi-mesa:amd64
     - libgles2-mesa:amd64
     - libglx-mesa0:amd64
     - libwayland-egl1-mesa:amd64
     - mesa-va-drivers:amd64
     - mesa-vdpau-drivers:amd64
     - mesa-vulkan-drivers:amd64
     - vulkan-utils
     - udev
   default_release: "{{ ansible_distribution_release }}-backports"
   update_cache: yes

# required to be done before steam is added to avoid package conflicts
- name: Install backported mesa i386
  apt:
   name:
     - libegl-mesa0:i386
     - libegl1-mesa:i386
     - libgbm1:i386
     - libgl1-mesa-dri:i386
     - libgl1-mesa-glx:i386
     - libglapi-mesa:i386
     - libgles2-mesa:i386
     - libglx-mesa0:i386
     - libwayland-egl1-mesa:i386
     - mesa-va-drivers:i386
     - mesa-vdpau-drivers:i386
     - mesa-vulkan-drivers:i386
     - udev:i386
   default_release: "{{ ansible_distribution_release }}-backports"


- name: Install backported kernel
  apt:
   name: "linux-image-{{ kernel_version }}"
   default_release: "{{ ansible_distribution_release }}-backports"
   state: present

# steam has a popup during installation from apt on Debian that
# asks for accepting a license
# https://askubuntu.com/questions/506909/how-can-i-accept-the-lience-agreement-for-steam-prior-to-apt-get-install
# required steam version 1.0.0.50
# only jessie has older than the required version(x.49)
#steam:
#  debconf.set:
#    - data:
#        steam/question: {'type': 'select', 'value': 'I AGREE'}
#        steam/license: {'type': 'note', 'value': ''}
#  pkg.installed:
#    - sources:
#      - steam-launcher: https://steamcdn-a.akamaihd.net/client/installer/steam.deb
#    - require:
#      - debconf: steam
#
# steam needs i386 backports packages installed before it can be installed
# otherwise it ends in package conflicts

# there's a debconf module
# https://docs.ansible.com/ansible/latest/modules/debconf_module.html
# https://stackoverflow.com/questions/19275856/auto-yes-to-the-license-agreement-on-sudo-apt-get-y-install-oracle-java7-instal

- name: accept steam license
  debconf:
    name: "steam"
    question: "steam/question"
    value: "I AGREE"
    vtype: "select"

- name: Install steam
  apt:
   name: steam
   state: present
   #dpkg_options: 'steam   steam/question  select  I AGREE,steam   steam/license   note'
